<?php


namespace rain1208\guildsAPI\forms;


use pocketmine\Player;
use rain1208\guildsAPI\forms\addons\AbstractMenuForm;

class MainForm extends AbstractMenuForm
{
    public function __construct()
    {
        $title = "Guild Main Form";
        $text = "";
        $options = [];
        parent::__construct($title, $text, $options);
    }

    public function submit(Player $player, int $select): void
    {
        // TODO: Implement submit() method.
    }

    public function close(Player $player)
    {
        parent::close($player); // TODO: Change the autogenerated stub
    }
}